/** Tier-1 worker identities — the largest curated agent-name pool. */
export interface Molecule {
  readonly ordinal: number;
  readonly name: string;
}

export const MOLECULES: readonly Molecule[] = [
  { ordinal: 1, name: 'Water' },
  { ordinal: 2, name: 'Methane' },
  { ordinal: 3, name: 'Ammonia' },
  { ordinal: 4, name: 'CarbonDioxide' },
  { ordinal: 5, name: 'Glucose' },
  { ordinal: 6, name: 'Sucrose' },
  { ordinal: 7, name: 'Ethanol' },
  { ordinal: 8, name: 'Methanol' },
  { ordinal: 9, name: 'Acetone' },
  { ordinal: 10, name: 'Benzene' },
  { ordinal: 11, name: 'Caffeine' },
  { ordinal: 12, name: 'Serotonin' },
  { ordinal: 13, name: 'Dopamine' },
  { ordinal: 14, name: 'Adrenaline' },
  { ordinal: 15, name: 'Insulin' },
  { ordinal: 16, name: 'Hemoglobin' },
  { ordinal: 17, name: 'Chlorophyll' },
  { ordinal: 18, name: 'DNA' },
  { ordinal: 19, name: 'RNA' },
  { ordinal: 20, name: 'ATP' },
  { ordinal: 21, name: 'Urea' },
  { ordinal: 22, name: 'Cholesterol' },
  { ordinal: 23, name: 'Testosterone' },
  { ordinal: 24, name: 'Estrogen' },
  { ordinal: 25, name: 'Cortisol' },
  { ordinal: 26, name: 'Melatonin' },
  { ordinal: 27, name: 'Histamine' },
  { ordinal: 28, name: 'Glycine' },
  { ordinal: 29, name: 'Alanine' },
  { ordinal: 30, name: 'Lysine' },
  { ordinal: 31, name: 'Tryptophan' },
  { ordinal: 32, name: 'Nicotine' },
  { ordinal: 33, name: 'Aspirin' },
  { ordinal: 34, name: 'Penicillin' },
  { ordinal: 35, name: 'Lactose' },
  { ordinal: 36, name: 'Fructose' },
  { ordinal: 37, name: 'Citrate' },
  { ordinal: 38, name: 'Oxytocin' },
  { ordinal: 39, name: 'Thyroxine' },
  { ordinal: 40, name: 'Keratin' },
  { ordinal: 41, name: 'Cellulose' },
  { ordinal: 42, name: 'Starch' },
  { ordinal: 43, name: 'Glycogen' },
  { ordinal: 44, name: 'Chitin' },
  { ordinal: 45, name: 'Lignin' },
  { ordinal: 46, name: 'Ribose' },
  { ordinal: 47, name: 'Deoxyribose' },
  { ordinal: 48, name: 'Galactose' },
  { ordinal: 49, name: 'Maltose' },
  { ordinal: 50, name: 'Trehalose' },
  { ordinal: 51, name: 'Mannose' },
  { ordinal: 52, name: 'Xylose' },
  { ordinal: 53, name: 'Pyruvate' },
  { ordinal: 54, name: 'Lactate' },
  { ordinal: 55, name: 'Acetate' },
  { ordinal: 56, name: 'Formate' },
  { ordinal: 57, name: 'Oxalate' },
  { ordinal: 58, name: 'Succinate' },
  { ordinal: 59, name: 'Fumarate' },
  { ordinal: 60, name: 'Malate' },
  { ordinal: 61, name: 'Glutamate' },
  { ordinal: 62, name: 'Aspartate' },
  { ordinal: 63, name: 'Valine' },
  { ordinal: 64, name: 'Leucine' },
  { ordinal: 65, name: 'Isoleucine' },
  { ordinal: 66, name: 'Serine' },
  { ordinal: 67, name: 'Threonine' },
  { ordinal: 68, name: 'Cysteine' },
  { ordinal: 69, name: 'Methionine' },
  { ordinal: 70, name: 'Phenylalanine' },
  { ordinal: 71, name: 'Tyrosine' },
  { ordinal: 72, name: 'Asparagine' },
  { ordinal: 73, name: 'Glutamine' },
  { ordinal: 74, name: 'Arginine' },
  { ordinal: 75, name: 'Histidine' },
  { ordinal: 76, name: 'Proline' },
  { ordinal: 77, name: 'Biotin' },
  { ordinal: 78, name: 'Thiamine' },
  { ordinal: 79, name: 'Riboflavin' },
  { ordinal: 80, name: 'Niacin' },
  { ordinal: 81, name: 'Pyridoxine' },
  { ordinal: 82, name: 'Folate' },
  { ordinal: 83, name: 'Retinol' },
  { ordinal: 84, name: 'Calciferol' },
  { ordinal: 85, name: 'Tocopherol' },
  { ordinal: 86, name: 'Phylloquinone' },
  { ordinal: 87, name: 'Adenine' },
  { ordinal: 88, name: 'Guanine' },
  { ordinal: 89, name: 'Cytosine' },
  { ordinal: 90, name: 'Thymine' },
  { ordinal: 91, name: 'Uracil' },
  { ordinal: 92, name: 'Adenosine' },
  { ordinal: 93, name: 'Guanosine' },
  { ordinal: 94, name: 'Cytidine' },
  { ordinal: 95, name: 'Thymidine' },
  { ordinal: 96, name: 'Uridine' },
  { ordinal: 97, name: 'AMP' },
  { ordinal: 98, name: 'ADP' },
  { ordinal: 99, name: 'NAD' },
  { ordinal: 100, name: 'NADH' },
  { ordinal: 101, name: 'FAD' },
  { ordinal: 102, name: 'CoenzymeA' },
  { ordinal: 103, name: 'AcetylCoA' },
  { ordinal: 104, name: 'Creatine' },
  { ordinal: 105, name: 'Creatinine' },
  { ordinal: 106, name: 'Taurine' },
  { ordinal: 107, name: 'GABA' },
  { ordinal: 108, name: 'Glutathione' },
  { ordinal: 109, name: 'Heme' },
  { ordinal: 110, name: 'Bilirubin' },
  { ordinal: 111, name: 'Menthol' },
  { ordinal: 112, name: 'Limonene' },
  { ordinal: 113, name: 'Vanillin' },
  { ordinal: 114, name: 'Capsaicin' },
  { ordinal: 115, name: 'Curcumin' },
  { ordinal: 116, name: 'Quercetin' },
  { ordinal: 117, name: 'Resveratrol' },
  { ordinal: 118, name: 'Lycopene' },
];

export function nextAvailableMolecule(
  used: Set<number>,
  taken: ReadonlySet<string> = new Set()
): { ordinal: number; name: string } {
  for (const m of MOLECULES) {
    if (!used.has(m.ordinal) && !taken.has(m.name)) {
      return { ordinal: m.ordinal, name: m.name };
    }
  }
  let n = MOLECULES.length + 1;
  while (used.has(n) || taken.has(`Molecule${n}`)) n++;
  return { ordinal: n, name: `Molecule${n}` };
}
